[package]
name = "game_server"
version = "0.1.0"
authors = ["j.tochikawa"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
big_s = "1.0.2"
lazy_static = "1.4.0"
maplit = "1.0.2"